version: "2.2"
services:
    sf2cs-redis:
      container_name: sf2cs-redis
      image: redis:5
      ports: 
        - 6379:6379
      volumes: 
        # docker volumes mapping
        - "${REDIS_DIR}/conf:/usr/local/etc/redis"
        - "${REDIS_DIR}/data:/data"
      command: 
        redis-server
      restart: always
    sf2cs-mysql:
      container_name: sf2cs-mysql
      image: mysql:8
      ports:
        - 3306:3306
      volumes:
        - "${MYSQL_DIR}/data:/var/lib/mysql"
        - "${MYSQL_DIR}/conf.d:/etc/mysql/conf.d"
      environment:
        # environment variables
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}